scheme_version: 1
server_url: https://10.0.5.131:443
token: 'Bucetao!86'
os:
  ssh_authorized_keys:
    - github:felipedbene
  hostname: harv4
  modules:
    - kvm
    - nvme
  sysctls:
    kernel.printk: "4 4 1 7"
    kernel.kptr_restrict: "1"
  dns_nameservers:
    - 10.0.5.1
  ntp_servers:
    - 0.suse.pool.ntp.org
    - 1.suse.pool.ntp.org
  password: N0m4m3s!86
  environment:
    http_proxy:
    https_proxy: 
install:
  mode: create
  management_interface:
    interfaces:
    - name: enp8s0
      hwAddr: "00:13:32:08:fd:04"
    method: dhcp
  force_efi: true
  device: /dev/nvme0n1
  data_disk: /dev/nvme0n1
  silent: true
  iso_url: iso_url: https://releases.rancher.com/harvester/v1.4.0/harvester-v1.4.0-amd64.iso
  poweroff: true
  no_format: true
  debug: true
  tty: ttyS0
  vip: 10.0.5.100
  vip_hw_addr: 52:54:00:ec:0e:0b
  vip_mode: dhcp
  force_mbr: false
  addons:
    harvester_vm_import_controller:
      enabled: false
      values_content: ""
    harvester_pcidevices_controller:
      enabled: false
      values_content: ""
    rancher_monitoring:
      enabled: true
      values_content: ""
    rancher_logging:
      enabled: true
      values_content: ""
    harvester_seeder:
      enabled: false
      values_content: ""
system_settings:
  auto-disk-provision-paths: ""